#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC =  -Iinclude
CFLAGS =  -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -g -D_DEBUG
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/sat2

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O2
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj
DEP_RELEASE = 
OUT_RELEASE = bin/sat2

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/SMT/SMT.o $(OBJDIR_DEBUG)/src/arith/arith.o $(OBJDIR_DEBUG)/src/enigme/latin.o $(OBJDIR_DEBUG)/src/enigme/magic.o $(OBJDIR_DEBUG)/src/enigme/sudoku.o $(OBJDIR_DEBUG)/src/kcolor/kcolor.o $(OBJDIR_DEBUG)/src/main.o $(OBJDIR_DEBUG)/src/tseitin/tseitin.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/SMT/SMT.o $(OBJDIR_RELEASE)/src/arith/arith.o $(OBJDIR_RELEASE)/src/enigme/latin.o $(OBJDIR_RELEASE)/src/enigme/magic.o $(OBJDIR_RELEASE)/src/enigme/sudoku.o $(OBJDIR_RELEASE)/src/kcolor/kcolor.o $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/src/tseitin/tseitin.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src/SMT || mkdir -p $(OBJDIR_DEBUG)/src/SMT
	test -d $(OBJDIR_DEBUG)/src/arith || mkdir -p $(OBJDIR_DEBUG)/src/arith
	test -d $(OBJDIR_DEBUG)/src/enigme || mkdir -p $(OBJDIR_DEBUG)/src/enigme
	test -d $(OBJDIR_DEBUG)/src/kcolor || mkdir -p $(OBJDIR_DEBUG)/src/kcolor
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG)/src/tseitin || mkdir -p $(OBJDIR_DEBUG)/src/tseitin

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/SMT/SMT.o: src/SMT/SMT.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SMT/SMT.cpp -o $(OBJDIR_DEBUG)/src/SMT/SMT.o

$(OBJDIR_DEBUG)/src/arith/arith.o: src/arith/arith.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/arith/arith.cpp -o $(OBJDIR_DEBUG)/src/arith/arith.o

$(OBJDIR_DEBUG)/src/enigme/latin.o: src/enigme/latin.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/enigme/latin.cpp -o $(OBJDIR_DEBUG)/src/enigme/latin.o

$(OBJDIR_DEBUG)/src/enigme/magic.o: src/enigme/magic.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/enigme/magic.cpp -o $(OBJDIR_DEBUG)/src/enigme/magic.o

$(OBJDIR_DEBUG)/src/enigme/sudoku.o: src/enigme/sudoku.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/enigme/sudoku.cpp -o $(OBJDIR_DEBUG)/src/enigme/sudoku.o

$(OBJDIR_DEBUG)/src/kcolor/kcolor.o: src/kcolor/kcolor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/kcolor/kcolor.cpp -o $(OBJDIR_DEBUG)/src/kcolor/kcolor.o

$(OBJDIR_DEBUG)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/src/main.o

$(OBJDIR_DEBUG)/src/tseitin/tseitin.o: src/tseitin/tseitin.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/tseitin/tseitin.cpp -o $(OBJDIR_DEBUG)/src/tseitin/tseitin.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src/SMT
	rm -rf $(OBJDIR_DEBUG)/src/arith
	rm -rf $(OBJDIR_DEBUG)/src/enigme
	rm -rf $(OBJDIR_DEBUG)/src/kcolor
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)/src/tseitin

before_release: 
	test -d bin || mkdir -p bin
	test -d $(OBJDIR_RELEASE)/src/SMT || mkdir -p $(OBJDIR_RELEASE)/src/SMT
	test -d $(OBJDIR_RELEASE)/src/arith || mkdir -p $(OBJDIR_RELEASE)/src/arith
	test -d $(OBJDIR_RELEASE)/src/enigme || mkdir -p $(OBJDIR_RELEASE)/src/enigme
	test -d $(OBJDIR_RELEASE)/src/kcolor || mkdir -p $(OBJDIR_RELEASE)/src/kcolor
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE)/src/tseitin || mkdir -p $(OBJDIR_RELEASE)/src/tseitin

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/SMT/SMT.o: src/SMT/SMT.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SMT/SMT.cpp -o $(OBJDIR_RELEASE)/src/SMT/SMT.o

$(OBJDIR_RELEASE)/src/arith/arith.o: src/arith/arith.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/arith/arith.cpp -o $(OBJDIR_RELEASE)/src/arith/arith.o

$(OBJDIR_RELEASE)/src/enigme/latin.o: src/enigme/latin.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/enigme/latin.cpp -o $(OBJDIR_RELEASE)/src/enigme/latin.o

$(OBJDIR_RELEASE)/src/enigme/magic.o: src/enigme/magic.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/enigme/magic.cpp -o $(OBJDIR_RELEASE)/src/enigme/magic.o

$(OBJDIR_RELEASE)/src/enigme/sudoku.o: src/enigme/sudoku.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/enigme/sudoku.cpp -o $(OBJDIR_RELEASE)/src/enigme/sudoku.o

$(OBJDIR_RELEASE)/src/kcolor/kcolor.o: src/kcolor/kcolor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/kcolor/kcolor.cpp -o $(OBJDIR_RELEASE)/src/kcolor/kcolor.o

$(OBJDIR_RELEASE)/src/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/src/main.o

$(OBJDIR_RELEASE)/src/tseitin/tseitin.o: src/tseitin/tseitin.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/tseitin/tseitin.cpp -o $(OBJDIR_RELEASE)/src/tseitin/tseitin.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin
	rm -rf $(OBJDIR_RELEASE)/src/SMT
	rm -rf $(OBJDIR_RELEASE)/src/arith
	rm -rf $(OBJDIR_RELEASE)/src/enigme
	rm -rf $(OBJDIR_RELEASE)/src/kcolor
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)/src/tseitin

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

